/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Jan 18, 2015, 3:24:30 PM
 */
package com.chatapp.view;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author SAWSAN
 */
public class MainWindow extends javax.swing.JFrame {

    ImageIcon online = new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("online1.png")).getScaledInstance(25, 25, Image.SCALE_SMOOTH));
    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Messenger_icon.png")).getScaledInstance(80, 80, Image.SCALE_SMOOTH));
        setSize(320,720);
        setBackground(new Color(0, 153, 153));
        userStatusLabel.setIcon(online);
        DefaultListModel listmodel = new DefaultListModel();
        listmodel.addElement(new FriendPanal());
        //freindsList.setModel(listmodel);
        friendsList.setCellRenderer(new FriendListCellRenderer());
        friendsList.add(new FriendPanal());
        friendsList.add(new FriendPanal());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        userInfoPanel = new javax.swing.JPanel();
        userIconLabel = new javax.swing.JLabel();
        userStatusLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        friendsListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendsList = new javax.swing.JList();
        updatesPanel = new javax.swing.JPanel();
        advertisePanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        messengerMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        contactsMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        actionsMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hmss Messenger");
        setBackground(new java.awt.Color(0, 153, 153));
        setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().setLayout(null);

        userInfoPanel.setBackground(new java.awt.Color(0, 153, 153));

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ChatAppha/view/default_icon.gif"))); // NOI18N

        userStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ChatAppha/view/online1.png"))); // NOI18N
        userStatusLabel.setText("jLabel1");

        userNameLabel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("SAWSAN");

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "   ", "available", "busy", "away" }));

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addComponent(userStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userStatusLabel)
                            .addComponent(userNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userIconLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(userInfoPanel);
        userInfoPanel.setBounds(0, 29, 330, 90);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        friendsListPanel.setBackground(new java.awt.Color(0, 153, 153));

        friendsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "AYA", "SARA" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(friendsList);

        javax.swing.GroupLayout friendsListPanelLayout = new javax.swing.GroupLayout(friendsListPanel);
        friendsListPanel.setLayout(friendsListPanelLayout);
        friendsListPanelLayout.setHorizontalGroup(
            friendsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        friendsListPanelLayout.setVerticalGroup(
            friendsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendsListPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contacts", friendsListPanel);

        updatesPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout updatesPanelLayout = new javax.swing.GroupLayout(updatesPanel);
        updatesPanel.setLayout(updatesPanelLayout);
        updatesPanelLayout.setHorizontalGroup(
            updatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        updatesPanelLayout.setVerticalGroup(
            updatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Updates", updatesPanel);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 120, 330, 460);

        advertisePanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout advertisePanelLayout = new javax.swing.GroupLayout(advertisePanel);
        advertisePanel.setLayout(advertisePanelLayout);
        advertisePanelLayout.setHorizontalGroup(
            advertisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        advertisePanelLayout.setVerticalGroup(
            advertisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(advertisePanel);
        advertisePanel.setBounds(0, 574, 330, 120);

        jToolBar1.setBackground(new java.awt.Color(0, 153, 153));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setText("jButton3");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 330, 30);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));
        jMenuBar1.setFont(new java.awt.Font("Khmer UI", 0, 12)); // NOI18N

        messengerMenu.setForeground(new java.awt.Color(255, 255, 255));
        messengerMenu.setText("Messenger");
        messengerMenu.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Sign out");
        messengerMenu.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setText("Exit");
        messengerMenu.add(jMenuItem2);

        jMenuBar1.add(messengerMenu);

        contactsMenu.setForeground(new java.awt.Color(255, 255, 255));
        contactsMenu.setText("Contacts");
        contactsMenu.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setText("Add Contact");
        contactsMenu.add(jMenuItem4);

        jMenuBar1.add(contactsMenu);

        actionsMenu.setForeground(new java.awt.Color(255, 255, 255));
        actionsMenu.setText("Actions");
        actionsMenu.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jMenuBar1.add(actionsMenu);

        helpMenu.setForeground(new java.awt.Color(255, 255, 255));
        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        jMenuItem3.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setText("About");
        helpMenu.add(jMenuItem3);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionsMenu;
    private javax.swing.JPanel advertisePanel;
    private javax.swing.JMenu contactsMenu;
    private javax.swing.JList friendsList;
    private javax.swing.JPanel friendsListPanel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu messengerMenu;
    private javax.swing.JPanel updatesPanel;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userStatusLabel;
    // End of variables declaration//GEN-END:variables
}
